targets:
  - name: test
    context: kind-test
  - name: prod
    context: kind-prod
  - name: eks
    context: kluctl-demo

discriminator: cluster-gitops-{{ target.name }}

args:
  - name: kluctl_version
    default: v2.21.0-devel
