targets:
  - name: test
    context: kind-test
    args:
      kluctl_version: v2.21.0-snapshot-demo
  - name: prod
    context: kind-prod
  - name: eks
    context: kluctl-demo
    args:
      kluctl_version: v2.21.0-snapshot-demo

discriminator: cluster-gitops-{{ target.name }}

args:
  - name: kluctl_version
    default: v2.21.0-devel
