apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-controller
  namespace: kluctl-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: template-controller
  namespace: kluctl-system
rules:
  - apiGroups: ["templates.kluctl.io/v1alpha1", "gitops.kluctl.io/v1beta1"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: template-controller
  namespace: kluctl-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: template-controller
subjects:
  - kind: ServiceAccount
    name: template-controller
