apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops
  namespace: gitops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops
  namespace: kluctl-system
rules:
  - apiGroups: ["templates.kluctl.io/v1alpha1", "gitops.kluctl.io/v1beta1"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops
  namespace: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops
subjects:
  - kind: ServiceAccount
    name: gitops
