apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: clusters-gitops
  namespace: kluctl-system
spec:
  interval: 1m
  timeout: 5m

  source:
    url: https://github.com/codablock/kluctl-clusters-gitops.git

  target: {{ target.name }}
  context: default

  prune: true
